/**
 * The activity catalogue.
 *
 * A slug appears in four places and they have to agree: the dashboard route
 * that frames the activity, the player route that runs it, the directory of the
 * same name in the asset bucket, and the tile art in `public/thumbnails`.
 *
 * Every activity is a static bundle (HTML, WASM, Unity, Flash) that we serve and
 * never build. There are hundreds, so nothing about one is hand-written: the
 * whole set is generated by `scripts/build-catalogue.mjs` into
 * `activities.catalogue.json`, and this module is the typed view over it.
 *
 * ## Why this is `server-only`
 *
 * The catalogue is signed-in content. It used to be imported directly by
 * `ActivitiesBrowser` and `HomeBoard`, both `"use client"`, which put all 318
 * entries into a `/_next/static/*` chunk — and those chunks are served flat,
 * with no session behind them. The routes were gated; the data was not. Anyone
 * who knew the chunk URL could read the whole index without an account.
 *
 * `import "server-only"` is what keeps that from coming back. It is not a
 * convention a future edit can quietly ignore: a `"use client"` module that
 * imports this file fails the build, with the import chain in the error. The
 * client gets its activities as props instead — serialised into the RSC payload
 * of a route that has already called `auth.protect()`, which is the one path
 * that cannot be fetched without a session.
 *
 * The type and the pure per-activity helpers live in `src/lib/activity.ts`,
 * which is free of the data and safe for either side. Import from there in
 * anything a browser runs.
 *
 * There was briefly a second kind — an activity compiled into the app's own bundle
 * and rendered by the player route — carried as a discriminated union on a
 * `runtime` field. It is gone, and so is the union. If one comes back, the
 * shape to restore is a `runtime` discriminant here, a component under
 * `src/components/activity/`, a branch in `src/app/learn/[slug]/page.tsx`, and
 * the `postMessage` score listener in `ActivityFrame`.
 */

import "server-only";

import catalogue from "@/lib/activities.catalogue.json";
import type { Activity, Genre } from "@/lib/activity";
import type { ActivityEntry } from "@/components/app/search-provider";

// Re-exported so a Server Component that already needs the catalogue does not
// have to import its type from a second module.
export type { Activity, Genre };

/**
 * The catalogue, in upstream's own order.
 *
 * The JSON is cast rather than validated at runtime: it is generated by a
 * script in this repo and committed, so a bad value is a build-time problem
 * that `tsc` and the generator's own assertions catch, not a request-time one
 * worth paying for on every render.
 */
export const ACTIVITIES: readonly Activity[] = catalogue as Activity[];

const BY_SLUG = new Map(
  ACTIVITIES.map((activity) => [activity.slug, activity]),
);

export function findActivity(slug: string): Activity | undefined {
  return BY_SLUG.get(slug);
}

/**
 * The catalogue, narrowed to what a search result row needs.
 *
 * This is the shape the dashboard layout hands `SearchProvider`, so the rail's
 * search can find an activity from any page of the app rather than only from
 * the one that already has the grid. Three fields rather than the whole
 * `Activity`, because the list travels in every dashboard page's RSC payload
 * and a result row draws none of the rest — see `ActivityEntry` for the same
 * argument from the other side.
 */
export function searchableActivities(): ActivityEntry[] {
  return ACTIVITIES.map(({ slug, title, genre }) => ({ slug, title, genre }));
}
