/**
 * The single source of truth for the brand: name, voice, canonical URL, and
 * the geometry of the Rift logotype and mark. Everything else — the favicon, the app
 * icons, the OG image, the header lockup — is derived from here, so the brand
 * can only ever be changed in one place.
 *
 * The domain is not spelled out here. `url` resolves from
 * `NEXT_PUBLIC_SITE_URL` and falls back to `config/domains.json`, which is the
 * only place in the repo a domain literal lives, and `domain` is derived from
 * `url` rather than stored beside it. That derivation is the point: the role
 * addresses in `src/lib/legal.ts` and `src/lib/content.ts` are built on
 * `domain`, so a stored copy would go stale the moment the site moved and the
 * symptom would be a privacy policy quoting an address that no longer accepts
 * mail. See `config/domains.md`.
 */

import domains from "@config/domains.json";
import { withoutTrailingSlash } from "@/lib/origin";

/** The site's configured origin, falling back to the canonical domain. */
function resolveUrl(): string {
  return withoutTrailingSlash(process.env.NEXT_PUBLIC_SITE_URL ?? domains.site);
}

/**
 * Hosts that are a deployment, not a brand.
 *
 * `url` is whatever origin this deployment answers on, which on a preview is a
 * generated `*.vercel.app` name and locally is `localhost:3000`. Those are
 * correct answers for a canonical URL and useless ones for an email address:
 * a privacy policy is a document a reader may act on, and rendering
 * `privacy@localhost:3000` in one is worse than rendering a stale domain,
 * because the stale domain at least looks like something a person could write
 * to. So the derivation covers the production case and declines the rest.
 */
function isDeploymentHost(host: string): boolean {
  return (
    host === "localhost" ||
    host.startsWith("localhost:") ||
    host.startsWith("127.0.0.1") ||
    host.endsWith(".vercel.app")
  );
}

/**
 * The bare domain the role addresses sit on.
 *
 * Derived from `url`, with `NEXT_PUBLIC_BRAND_DOMAIN` as the escape hatch for
 * the one case where the two genuinely differ: a cutover where the site has
 * moved and mail has not. Without that override the choice would be between
 * moving both at once or hard-coding one of them again — and hard-coding is
 * exactly what leaves a privacy policy quoting an address that stopped
 * accepting mail two domains ago.
 */
function resolveDomain(url: string): string {
  const override = process.env.NEXT_PUBLIC_BRAND_DOMAIN ?? domains.mail;
  if (override)
    return withoutTrailingSlash(override.replace(/^https?:\/\//, ""));

  const fallback = new URL(domains.site).host;
  try {
    const host = new URL(url).host;
    return isDeploymentHost(host) ? fallback : host;
  } catch {
    return fallback;
  }
}

const url = resolveUrl();

export const brand = {
  name: "Rift",
  /** Used where the full name will not fit: app icon labels, tab titles. */
  shortName: "Rift",
  tagline: "The visual learning platform",
  description:
    "Rift turns dense course material into concept maps, animated walkthroughs, and practice that adapts to what you have not understood yet.",
  /** Kept short enough to survive Google's ~155 character description clamp. */
  metaDescription:
    "Turn dense course material into concept maps, animated walkthroughs, and practice that adapts to what you have not understood yet.",
  domain: resolveDomain(url),
  url,
  locale: "en_US",
  colors: {
    /** The mark is always pure black on pure white — never tinted. */
    ink: "#0f0f0f",
    paper: "#ffffff",
    /** Browser chrome colour, per theme. */
    themeLight: "#ffffff",
    themeDark: "#0f0f0f",
  },
} as const;

/**
 * The Rift mark, on a 100x100 canvas: the R from the logotype on its own —
 * Inter ExtraBold, slanted 10°. The R is taller than it is wide, so
 * `inkBox` is its true bounds, which is what `LogoMark` crops to.
 *
 * Generated by `scripts/generate-brand-assets.py`, which also writes the SVG
 * assets and rasterises the rest; change the letters there and paste the
 * printed values back here.
 */
export const mark = {
  viewBox: "0 0 100 100",
  /** The ink box, for lockups that must not inherit the canvas padding. */
  inkBox: "15.87 12 68.26 76",
  /** Corner radius of the containing tile, in canvas units. */
  tileRadius: 20,
  path: "M38.49 61.83 48.26 61.83 57.6 88 77.34 88 66.6 58.99 68.85 57.95 71.91 56.13 74.66 53.98 77.11 51.49 79.24 48.68 80.46 46.64 81.5 44.48 82.76 41.01 83.63 37.25 84.08 33.5 84.13 31.15 83.81 27.84 83.02 24.79 81.78 22.02 80.13 19.56 78.05 17.43 76.44 16.19 74.64 15.09 71.62 13.74 68.23 12.77 64.49 12.19 60.39 12 29.27 12 15.87 88 33.88 88ZM44.71 26.59 56.01 26.66 57.83 26.89 60.42 27.6 62.45 28.71 63.41 29.58 64.16 30.58 64.72 31.73 65.06 33.03 65.17 35.54 64.96 37.25 64.58 38.93 64.03 40.46 63.34 41.84 62.17 43.44 60.33 45.07 58.57 46.07 56.01 46.97 53.65 47.41 51.71 47.57 41 47.6Z",
} as const;

/**
 * The Rift logotype: "Rift" in Inter ExtraBold, slanted 10°, with one band
 * strung through the i, f and t at crossbar height — it is their crossbar,
 * carried through — ending past the t in a point. Slashes cut the band
 * between the letters, so they read as joined and are not. The viewBox is the
 * ink itself, at cap height 100.
 *
 * Generated alongside `mark`, from the same outlines.
 */
export const logotype = {
  viewBox: "0 0 257.53 107.4",
  path: "M119.52 21.71 121.76 20.68 123.19 19.76 125.17 18.1 126.76 16.25 127.58 14.92 128.48 12.78 128.96 10.47 128.98 8.24 128.73 6.86 127.96 4.95 126.71 3.23 125.09 1.81 123.86 1.09 121.82 0.34 119.51 0 117.06 0.07 114.7 0.55 112.44 1.44 110.28 2.74 107.72 5 106.28 6.91 105.24 8.99 104.51 12.02 104.5 14.19 104.96 16.21 105.89 18.06 106.78 19.21 107.82 20.22 109.6 21.4 111.62 22.16 113.9 22.5 117.17 22.32ZM130.74 106.35 154.03 106.35 164.19 48.7 170.01 48.7 184.8 31.32 167.26 31.32 168.11 26.55 168.55 25.05 169.4 23.32 170.56 21.89 171.69 21.05 173.09 20.46 175.38 20.03 177.61 20 179.98 20.23 183.32 20.92 190.1 3.8 185.28 2.68 180.26 1.92 175.53 1.66 171.02 1.83 167.5 2.36 163.04 3.61 158.88 5.49 156.05 7.32 153.47 9.52 151.14 12.07 149.09 14.98 147.9 17.12 146.87 19.42 145.61 23.18 144.95 25.88 143.97 31.32 142.45 31.32 127.66 48.7 140.9 48.7ZM174.3 48.7 191.84 48.7 185.36 85.48 184.92 88.92 184.88 92.07 185.23 94.94 185.98 97.52 187.12 99.81 188.65 101.82 189.56 102.72 191.67 104.27 194.15 105.52 195.53 106.03 198.57 106.8 201.99 107.27 207.46 107.4 213.46 106.95 218.03 106.16 220.76 105.48 220.74 88.43 218.24 88.88 215.01 89.21 213.1 89.2 211.81 88.99 210.48 88.43 209.78 87.8 209.31 86.98 209 85.6 209.15 83.4 215.27 48.7 238.82 48.7 257.53 31.32 218.33 31.32 221.48 13.47 198.06 13.47 194.91 31.32 189.09 31.32ZM138.15 31.32 101.49 31.32 88.26 106.35 111.68 106.35 121.84 48.7 123.36 48.7ZM66.75 68.18 69.71 66.81 73.73 64.42 77.36 61.59 79.55 59.45 82.5 55.89 84.21 53.3 85.69 50.54 87.51 46.09 88.83 41.27 89.62 36.25 89.81 33.08 89.6 28.61 88.77 24.48 87.87 21.92 86.72 19.53 84.54 16.3 82.78 14.39 80.78 12.66 78.53 11.11 76.05 9.77 73.35 8.64 70.43 7.73 65.67 6.8 62.23 6.47 58.57 6.35 17.63 6.35 0 106.35 23.69 106.35 29.76 71.92 42.62 71.92 54.9 106.35 80.87 106.35ZM53.64 25.72 57.33 26.44 60.31 27.69 61.74 28.7 62.91 29.9 63.81 31.29 64.27 32.32 64.72 34.03 64.87 35.28 64.87 37.33 64.59 39.57 63.63 43.15 62.78 45.03 61.73 46.71 60.01 48.64 57.95 50.22 55.55 51.47 52.07 52.54 49.71 52.94 47.16 53.16 33.06 53.2 37.94 25.55 50.15 25.55Z",
} as const;
