/**
 * The single source of truth for the brand: name, voice, canonical URL, and
 * the geometry of the Rift airplane mark. Everything else — the favicon, the app
 * icons, the OG image, the header lockup — is derived from here, so the brand
 * can only ever be changed in one place.
 *
 * The domain is not spelled out here. `url` resolves from
 * `NEXT_PUBLIC_SITE_URL` and falls back to `config/domains.json`, which is the
 * only place in the repo a domain literal lives, and `domain` is derived from
 * `url` rather than stored beside it. That derivation is the point: the role
 * addresses in `src/lib/legal.ts` and `src/lib/content.ts` are built on
 * `domain`, so a stored copy would go stale the moment the site moved and the
 * symptom would be a privacy policy quoting an address that no longer accepts
 * mail. See `config/domains.md`.
 */

import domains from "@config/domains.json";
import { withoutTrailingSlash } from "@/lib/origin";

/** The site's configured origin, falling back to the canonical domain. */
function resolveUrl(): string {
  return withoutTrailingSlash(process.env.NEXT_PUBLIC_SITE_URL ?? domains.site);
}

/**
 * Hosts that are a deployment, not a brand.
 *
 * `url` is whatever origin this deployment answers on, which on a preview is a
 * generated `*.vercel.app` name and locally is `localhost:3000`. Those are
 * correct answers for a canonical URL and useless ones for an email address:
 * a privacy policy is a document a reader may act on, and rendering
 * `privacy@localhost:3000` in one is worse than rendering a stale domain,
 * because the stale domain at least looks like something a person could write
 * to. So the derivation covers the production case and declines the rest.
 */
function isDeploymentHost(host: string): boolean {
  return (
    host === "localhost" ||
    host.startsWith("localhost:") ||
    host.startsWith("127.0.0.1") ||
    host.endsWith(".workers.dev") ||
    host.endsWith(".vercel.app")
  );
}

/**
 * The bare domain the role addresses sit on.
 *
 * Derived from `url`, with `NEXT_PUBLIC_BRAND_DOMAIN` as the escape hatch for
 * the one case where the two genuinely differ: a cutover where the site has
 * moved and mail has not. Without that override the choice would be between
 * moving both at once or hard-coding one of them again — and hard-coding is
 * exactly what leaves a privacy policy quoting an address that stopped
 * accepting mail two domains ago.
 */
function resolveDomain(url: string): string {
  const override = process.env.NEXT_PUBLIC_BRAND_DOMAIN ?? domains.mail;
  if (override)
    return withoutTrailingSlash(override.replace(/^https?:\/\//, ""));

  const fallback = new URL(domains.site).host;
  try {
    const host = new URL(url).host;
    return isDeploymentHost(host) ? fallback : host;
  } catch {
    return fallback;
  }
}

const url = resolveUrl();

export const brand = {
  name: "Rift",
  /** Used where the full name will not fit: app icon labels, tab titles. */
  shortName: "Rift",
  tagline: "The visual learning platform",
  description:
    "Rift turns dense course material into concept maps, animated walkthroughs, and practice that adapts to what you have not understood yet.",
  /** Kept short enough to survive Google's ~155 character description clamp. */
  metaDescription:
    "Turn dense course material into concept maps, animated walkthroughs, and practice that adapts to what you have not understood yet.",
  domain: resolveDomain(url),
  url,
  locale: "en_US",
  colors: {
    /** The mark is always pure black on pure white — never tinted. */
    ink: "#0f0f0f",
    paper: "#ffffff",
    /** Browser chrome colour, per theme. */
    themeLight: "#ffffff",
    themeDark: "#0f0f0f",
  },
} as const;

/**
 * The Rift mark, on a 100x100 canvas: a swept-wing jet climbing at 45°, with
 * a hairline rift cut down the spine of the fuselage.
 *
 * The outline is two subpaths — the aircraft, then the needle-shaped rift —
 * and must be filled `evenodd` so the second punches through the first. The
 * rift tapers to a point at both ends and never reaches the nose or the tail,
 * so the silhouette stays one piece: at favicon sizes the cut falls below a
 * pixel and the mark degrades gracefully into a plain jet. The ink box is
 * exactly 12..88 on both axes, which is what `LogoMark` crops to.
 *
 * Generated by `scripts/generate-brand-assets.py`, which also rasterises it;
 * change the geometry there and paste the printed path back here.
 */
export const mark = {
  viewBox: "0 0 100 100",
  /** The ink box, for lockups that must not inherit the canvas padding. */
  inkBox: "12 12 76 76",
  /** Corner radius of the containing tile, in canvas units. */
  tileRadius: 20,
  path: "M87.86 12.14 88 13.55 87.93 15.01 87.65 16.51 87.16 18.06 86.46 19.66 85.55 21.3 84.44 22.99 83.11 24.72 81.57 26.5 79.83 28.33 70.9 37.26 75.75 81.63 71.61 85.77 55.6 52.56 38.26 67.09 39.09 85.13 36.22 88 26.98 73.02 12 63.78 14.87 60.91 32.91 61.74 47.44 44.4 14.23 28.39 18.37 24.25 62.74 29.1 71.67 20.17 73.5 18.43 75.28 16.89 77.01 15.56 78.7 14.45 80.34 13.54 81.94 12.84 83.49 12.35 84.99 12.07 86.45 12ZM74.47 25.53 55.16 43.18 34.31 65.69 56.82 44.84Z",
} as const;
