/**
 * The game catalogue.
 *
 * A slug appears in four places and they have to agree: the dashboard route
 * that frames the game, the player route that runs it, the directory of the
 * same name in the asset bucket, and the tile art in `public/thumbnails`.
 *
 * Every game is a static bundle (HTML, WASM, Unity, Flash) that we serve and
 * never build. There are hundreds, so nothing about one is hand-written: the
 * whole set is generated by `scripts/build-catalogue.mjs` into
 * `games.catalogue.json`, and this module is the typed view over it.
 *
 * There was briefly a second kind — a game compiled into the app's own bundle
 * and rendered by the player route — carried as a discriminated union on a
 * `runtime` field. It is gone, and so is the union. If one comes back, the
 * shape to restore is a `runtime` discriminant here, a component under
 * `src/components/player/`, a branch in `src/app/player/[slug]/page.tsx`, and
 * the `postMessage` score listener in `GameFrame`.
 */

import catalogue from "@/lib/games.catalogue.json";

/** The six upstream settles on, after `build-catalogue.mjs` folds its typos
 *  and one-off tags into them. */
export type Genre =
  | "adventure"
  | "arcade"
  | "mobile"
  | "platformer"
  | "puzzle"
  | "simulation";

export type Game = {
  slug: string;
  /** Shown in the rail, on the tile, and as the page heading. */
  title: string;
  genre: Genre;
  /**
   * Position in the catalogue, ascending, and the app's only popularity
   * signal — upstream hand-orders its index most-played first and this
   * preserves that. `POPULAR_COUNT` slices the head of it.
   */
  rank: number;
  /** Filename under `public/thumbnails`. All of them are 480x100. */
  thumbnail: string;
  /** Directory size upstream, for the migration script's accounting. */
  bytes: number;
};

/**
 * The catalogue, in upstream's own order.
 *
 * The JSON is cast rather than validated at runtime: it is generated by a
 * script in this repo and committed, so a bad value is a build-time problem
 * that `tsc` and the generator's own assertions catch, not a request-time one
 * worth paying for on every render.
 */
export const GAMES: readonly Game[] = catalogue as Game[];

/** How many tiles the dashboard shows before you have to search. */
export const POPULAR_COUNT = 24;

/**
 * Tile art, served from `public/` rather than from the asset bucket.
 *
 * The bundles are in R2 because they are 4.85 GB and would blow both the
 * deployment file limit and the bandwidth allowance. The thumbnails are the
 * opposite case on every axis: 318 files and under 2 MB in total, six
 * kilobytes each. Against a 15,000-file deployment limit and a 100 GB monthly
 * transfer allowance, that is not a cost worth engineering around.
 *
 * What it buys is a failure mode. The grid is the app's own chrome, not game
 * content — so when the bucket is unreachable or misconfigured, the catalogue
 * should still render correctly and fail only at the point of pressing play.
 * Art loaded from the bucket makes an asset-origin problem look like a broken
 * page; art loaded from here keeps the blast radius at the thing that is
 * actually broken.
 *
 * It also makes the art atomic with the catalogue: both are in the same
 * commit, so a tile can never reference a thumbnail that a later migration
 * has not uploaded yet.
 */
export const THUMBNAIL_PATH = "/thumbnails";

/** Where a game's tile art lives. */
export function thumbnailSrc(game: Game): string {
  return `${THUMBNAIL_PATH}/${game.thumbnail}`;
}

const BY_SLUG = new Map(GAMES.map((game) => [game.slug, game]));

export function findGame(slug: string): Game | undefined {
  return BY_SLUG.get(slug);
}

/** The head of the catalogue — what the grid shows with an empty search box. */
export function popularGames(count: number = POPULAR_COUNT): readonly Game[] {
  return GAMES.slice(0, count);
}

/** Lower-cased and stripped of everything but letters and digits, so that
 *  "papa's" matches "papas" and "run 3" matches "run3". */
function normalise(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]/g, "");
}

/**
 * Substring search over title, slug, and genre, in catalogue order.
 *
 * Deliberately not fuzzy. With a few hundred short titles a plain contains-
 * match is both predictable and instant, and the ranking that matters — the
 * popular ones first — is already carried by the array's order. An empty
 * query is not a search: the caller shows `popularGames()` instead.
 */
export function searchGames(query: string): readonly Game[] {
  const needle = normalise(query);
  if (!needle) return GAMES;
  return GAMES.filter((game) =>
    normalise(`${game.title} ${game.slug} ${game.genre}`).includes(needle),
  );
}

/** A genre and everything in it, in catalogue order. */
export type Shelf = { genre: Genre; games: readonly Game[] };

/**
 * The catalogue grouped into shelves, most popular genre first.
 *
 * "Most popular genre" is the rank of its best game rather than how many games
 * it holds, because the two disagree and the first is the more useful answer:
 * arcade is the largest section by a distance, but the game everyone opens is
 * a platformer. Ordering by size would bury Slope six shelves down.
 *
 * Computed once at module load. It is a single pass over a few hundred frozen
 * entries and the result never changes, so there is nothing for a hook to
 * memoise per component.
 */
export const SHELVES: readonly Shelf[] = (() => {
  const byGenre = new Map<Genre, Game[]>();
  for (const game of GAMES) {
    const games = byGenre.get(game.genre);
    if (games) games.push(game);
    else byGenre.set(game.genre, [game]);
  }
  // GAMES is already rank-ascending, so each bucket is too and `games[0]` is
  // the genre's best-ranked entry.
  return [...byGenre.entries()]
    .map(([genre, games]) => ({ genre, games }))
    .sort((a, b) => a.games[0].rank - b.games[0].rank);
})();

/**
 * The line a tile shows under its title.
 *
 * The catalogue carries no per-game copy — upstream writes a title and nothing
 * else — so rather than invent a blurb this states the one fact we do have:
 * where the game sits in upstream's hand-ordered, most-played-first index.
 */
export function popularityLabel(game: Game): string {
  return `#${game.rank + 1} most played`;
}
